import "./globals.css";
import type { Metadata } from "next";
import { Roboto_Condensed, Open_Sans } from "next/font/google";

const openSans = Open_Sans({
  weight: ["300", "400", "700"],
  subsets: ["latin"],
});

export const robotoCondensed = Roboto_Condensed({
  weight: ["300", "400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${openSans.className} h-screen w-screen bg-secondary flex flex-col items-center justify-center`}
      >
        {children}
      </body>
    </html>
  );
}
